/**
 * MCP Forge — Storage Layer
 * Sprint 14, Tasks 2 + 8
 *
 * Manages adapter project persistence, the dedicated adapters area,
 * and the app registry for long-term memory.
 */

import { existsSync, mkdirSync, writeFileSync, readFileSync, readdirSync, rmSync } from 'fs';
import { join, resolve } from 'path';
import { app } from 'electron';
import { v4 as uuid } from 'uuid';
import { getDatabase } from '../db';
import type { AdapterProject, AppRecord, CapabilityType, TestResult } from './types';

// ─── Adapter Storage Area ───

const ADAPTERS_DIR_NAME = '.gdeveloper-adapters';

/**
 * Get the dedicated adapters directory.
 * Default: <userData>/.gdeveloper-adapters/
 */
export function getAdaptersRoot(): string {
  const saved = getDatabase().getSetting('adapters_root');
  if (saved && existsSync(saved)) return saved;

  const root = join(app.getPath('userData'), ADAPTERS_DIR_NAME);
  if (!existsSync(root)) mkdirSync(root, { recursive: true });
  return root;
}

/**
 * Save a generated adapter project to disk.
 * Creates the adapter directory, writes the MCP server source, and persists metadata.
 */
export function saveAdapterProject(project: AdapterProject): AdapterProject {
  const root = getAdaptersRoot();
  const adapterDir = join(root, project.name);

  if (!existsSync(adapterDir)) {
    mkdirSync(adapterDir, { recursive: true });
  }

  // Write generated MCP server code
  writeFileSync(join(adapterDir, 'server.ts'), project.generatedCode, 'utf-8');

  // Write package.json for the adapter
  const packageJson = {
    name: project.name,
    version: '1.0.0',
    description: `MCP server adapter for ${project.appName} — generated by GDeveloper MCP Forge`,
    main: 'server.ts',
    scripts: {
      start: 'npx tsx server.ts',
    },
    dependencies: {
      '@modelcontextprotocol/sdk': '^1.0.0',
    },
  };
  writeFileSync(join(adapterDir, 'package.json'), JSON.stringify(packageJson, null, 2), 'utf-8');

  // Write metadata
  const meta = {
    id: project.id,
    name: project.name,
    appName: project.appName,
    appPath: project.appPath,
    status: project.status,
    toolCount: project.tools.length,
    toolNames: project.tools.map(t => t.name),
    researchSummary: project.researchSummary,
    mcpServerId: project.mcpServerId,
    createdAt: project.createdAt,
    updatedAt: new Date().toISOString(),
    lastTestResult: project.lastTestResult,
  };
  writeFileSync(join(adapterDir, 'adapter-meta.json'), JSON.stringify(meta, null, 2), 'utf-8');

  // Write tools manifest
  writeFileSync(join(adapterDir, 'tools.json'), JSON.stringify(project.tools, null, 2), 'utf-8');

  // Update project path
  project.adapterPath = adapterDir;
  project.updatedAt = new Date().toISOString();

  const db = getDatabase();
  db.logActivity('system', 'forge_save', `Adapter saved: ${project.name}`, adapterDir, {
    adapterId: project.id, adapterDir,
  });

  return project;
}

/**
 * Load an adapter project from its directory.
 */
export function loadAdapterProject(adapterDir: string): AdapterProject | null {
  const metaPath = join(adapterDir, 'adapter-meta.json');
  if (!existsSync(metaPath)) return null;

  try {
    const meta = JSON.parse(readFileSync(metaPath, 'utf-8'));
    const serverCode = existsSync(join(adapterDir, 'server.ts'))
      ? readFileSync(join(adapterDir, 'server.ts'), 'utf-8')
      : '';
    const tools = existsSync(join(adapterDir, 'tools.json'))
      ? JSON.parse(readFileSync(join(adapterDir, 'tools.json'), 'utf-8'))
      : [];

    return {
      id: meta.id,
      name: meta.name,
      appName: meta.appName,
      appPath: meta.appPath,
      adapterPath: adapterDir,
      status: meta.status || 'draft',
      capabilities: { appName: meta.appName, appPath: meta.appPath, scanTimestamp: '', capabilities: [], recommendedStrategy: null, overallConfidence: 0, discoveredArtifacts: [], cliHelpOutput: '', warnings: [] },
      tools,
      generatedCode: serverCode,
      researchSummary: meta.researchSummary || '',
      mcpServerId: meta.mcpServerId || null,
      createdAt: meta.createdAt,
      updatedAt: meta.updatedAt,
      lastTestResult: meta.lastTestResult || null,
    };
  } catch {
    return null;
  }
}

/**
 * List all saved adapter projects.
 */
export function listAdapterProjects(): AdapterProject[] {
  const root = getAdaptersRoot();
  if (!existsSync(root)) return [];

  const projects: AdapterProject[] = [];
  try {
    for (const dir of readdirSync(root)) {
      const fullPath = join(root, dir);
      const project = loadAdapterProject(fullPath);
      if (project) projects.push(project);
    }
  } catch { /* ignore */ }

  return projects.sort((a, b) =>
    new Date(b.updatedAt).getTime() - new Date(a.updatedAt).getTime()
  );
}

/**
 * Update adapter project metadata (status, mcpServerId, etc.).
 */
export function updateAdapterProject(
  adapterId: string,
  updates: Partial<Pick<AdapterProject, 'status' | 'mcpServerId' | 'researchSummary' | 'tools' | 'generatedCode' | 'lastTestResult'>>
): AdapterProject | null {
  const projects = listAdapterProjects();
  const project = projects.find(p => p.id === adapterId);
  if (!project) return null;

  Object.assign(project, updates);
  project.updatedAt = new Date().toISOString();

  // Re-save to disk
  return saveAdapterProject(project);
}

/**
 * Remove an adapter project from disk.
 */
export function removeAdapterProject(adapterId: string): boolean {
  const projects = listAdapterProjects();
  const project = projects.find(p => p.id === adapterId);
  if (!project) return false;

  try {
    rmSync(project.adapterPath, { recursive: true, force: true });
    const db = getDatabase();
    db.logActivity('system', 'forge_remove', `Adapter removed: ${project.name}`, project.adapterPath, {
      adapterId: project.id,
    });
    return true;
  } catch {
    return false;
  }
}

// ─── App Registry (Task 8) ───

/**
 * Save or update an app record in the DB.
 */
export function saveAppRecord(record: Partial<AppRecord> & { appName: string; appPath: string }): AppRecord {
  const db = getDatabase();
  const existing = getAppRecordByPath(record.appPath);

  const fullRecord: AppRecord = {
    id: existing?.id || record.id || uuid(),
    appName: record.appName,
    appPath: record.appPath,
    capabilityTypes: record.capabilityTypes || existing?.capabilityTypes || [],
    adapterProjectId: record.adapterProjectId ?? existing?.adapterProjectId ?? null,
    adapterPath: record.adapterPath ?? existing?.adapterPath ?? null,
    generatedAt: record.generatedAt ?? existing?.generatedAt ?? null,
    lastTestResult: record.lastTestResult ?? existing?.lastTestResult ?? null,
    lastConnectionState: record.lastConnectionState ?? existing?.lastConnectionState ?? null,
    usageCount: record.usageCount ?? existing?.usageCount ?? 0,
    favorite: record.favorite ?? existing?.favorite ?? false,
    createdAt: existing?.createdAt || new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  };

  db.setSetting(`app_record_${fullRecord.id}`, JSON.stringify(fullRecord));
  // Also maintain an index
  const index = getAppRecordIndex();
  if (!index.includes(fullRecord.id)) {
    index.push(fullRecord.id);
    db.setSetting('app_record_index', JSON.stringify(index));
  }

  return fullRecord;
}

function getAppRecordIndex(): string[] {
  const db = getDatabase();
  const raw = db.getSetting('app_record_index');
  return raw ? JSON.parse(raw) : [];
}

export function getAppRecord(id: string): AppRecord | null {
  const db = getDatabase();
  const raw = db.getSetting(`app_record_${id}`);
  return raw ? JSON.parse(raw) : null;
}

export function getAppRecordByPath(appPath: string): AppRecord | null {
  const resolved = resolve(appPath);
  const ids = getAppRecordIndex();
  for (const id of ids) {
    const record = getAppRecord(id);
    if (record && resolve(record.appPath) === resolved) return record;
  }
  return null;
}

export function listAppRecords(): AppRecord[] {
  const ids = getAppRecordIndex();
  const records: AppRecord[] = [];
  for (const id of ids) {
    const record = getAppRecord(id);
    if (record) records.push(record);
  }
  return records.sort((a, b) =>
    new Date(b.updatedAt).getTime() - new Date(a.updatedAt).getTime()
  );
}

export function removeAppRecord(id: string): boolean {
  const db = getDatabase();
  const index = getAppRecordIndex();
  const newIndex = index.filter(i => i !== id);
  db.setSetting('app_record_index', JSON.stringify(newIndex));
  db.setSetting(`app_record_${id}`, '');
  return true;
}

export function toggleAppFavorite(id: string): boolean {
  const record = getAppRecord(id);
  if (!record) return false;
  record.favorite = !record.favorite;
  record.updatedAt = new Date().toISOString();
  const db = getDatabase();
  db.setSetting(`app_record_${id}`, JSON.stringify(record));
  return record.favorite;
}
